/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { ICurvePool, ICurvePoolInterface } from "../../interfaces/ICurvePool.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "uint256[2]",
        "name": "amounts",
        "type": "uint256[2]"
      },
      {
        "internalType": "uint256",
        "name": "min_mint_amount",
        "type": "uint256"
      }
    ],
    "name": "add_liquidity",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256[3]",
        "name": "amounts",
        "type": "uint256[3]"
      },
      {
        "internalType": "uint256",
        "name": "min_mint_amount",
        "type": "uint256"
      }
    ],
    "name": "add_liquidity",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "token",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  export class ICurvePool__factory {
    static readonly abi = _abi;
    static createInterface(): ICurvePoolInterface {
      return new Interface(_abi) as ICurvePoolInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): ICurvePool {
      return new Contract(address, _abi, runner) as unknown as ICurvePool;
    }
  }
  