/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { INotional, INotionalInterface } from "../../../Notional/interfaces/INotional.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "account",
        "type": "address"
      },
      {
        "components": [
          {
            "internalType": "enum INotional.DepositActionType",
            "name": "actionType",
            "type": "uint8"
          },
          {
            "internalType": "uint16",
            "name": "currencyId",
            "type": "uint16"
          },
          {
            "internalType": "uint256",
            "name": "depositActionAmount",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "withdrawAmountInternalPrecision",
            "type": "uint256"
          },
          {
            "internalType": "bool",
            "name": "withdrawEntireCashBalance",
            "type": "bool"
          },
          {
            "internalType": "bool",
            "name": "redeemToUnderlying",
            "type": "bool"
          },
          {
            "internalType": "bytes32[]",
            "name": "trades",
            "type": "bytes32[]"
          }
        ],
        "internalType": "struct INotional.BalanceActionWithTrades[]",
        "name": "actions",
        "type": "tuple[]"
      }
    ],
    "name": "batchBalanceAndTradeAction",
    "outputs": [],
    "stateMutability": "payable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "account",
        "type": "address"
      },
      {
        "internalType": "uint16",
        "name": "currencyId",
        "type": "uint16"
      },
      {
        "internalType": "uint256",
        "name": "amountExternalPrecision",
        "type": "uint256"
      }
    ],
    "name": "depositUnderlyingToken",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "payable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint16",
        "name": "currencyId",
        "type": "uint16"
      },
      {
        "internalType": "address",
        "name": "account",
        "type": "address"
      }
    ],
    "name": "getAccountBalance",
    "outputs": [
      {
        "internalType": "int256",
        "name": "",
        "type": "int256"
      },
      {
        "internalType": "int256",
        "name": "",
        "type": "int256"
      },
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "account",
        "type": "address"
      }
    ],
    "name": "getFreeCollateral",
    "outputs": [
      {
        "internalType": "int256",
        "name": "",
        "type": "int256"
      },
      {
        "internalType": "int256[]",
        "name": "",
        "type": "int256[]"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint16",
        "name": "currencyId",
        "type": "uint16"
      },
      {
        "internalType": "uint88",
        "name": "amountInternalPrecision",
        "type": "uint88"
      },
      {
        "internalType": "bool",
        "name": "redeemToUnderlying",
        "type": "bool"
      }
    ],
    "name": "withdraw",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  export class INotional__factory {
    static readonly abi = _abi;
    static createInterface(): INotionalInterface {
      return new Interface(_abi) as INotionalInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): INotional {
      return new Contract(address, _abi, runner) as unknown as INotional;
    }
  }
  