/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'CurveExample', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.CurveExample__factory>
getContractFactory(name: 'IWETH', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IWETH__factory>
getContractFactory(name: 'AaveExample', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.AaveExample__factory>
getContractFactory(name: 'ConvexExample', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ConvexExample__factory>
getContractFactory(name: 'IConvex', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IConvex__factory>
getContractFactory(name: 'NotionalExample', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.NotionalExample__factory>
getContractFactory(name: 'IWETH', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IWETH__factory>
getContractFactory(name: 'UniswapV3Example', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.UniswapV3Example__factory>
getContractFactory(name: 'IUniversalRouter', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IUniversalRouter__factory>
getContractFactory(name: 'IWETH', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IWETH__factory>
getContractFactory(name: 'Permit2', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.Permit2__factory>
getContractFactory(name: 'UniswapV4Example', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.UniswapV4Example__factory>
getContractFactory(name: 'ICurveExchange', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ICurveExchange__factory>
getContractFactory(name: 'ICurvePool', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ICurvePool__factory>
getContractFactory(name: 'INotional', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.INotional__factory>

  getContractAt(name: 'CurveExample', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.CurveExample>
getContractAt(name: 'IWETH', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IWETH>
getContractAt(name: 'AaveExample', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.AaveExample>
getContractAt(name: 'ConvexExample', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ConvexExample>
getContractAt(name: 'IConvex', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IConvex>
getContractAt(name: 'NotionalExample', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.NotionalExample>
getContractAt(name: 'IWETH', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IWETH>
getContractAt(name: 'UniswapV3Example', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.UniswapV3Example>
getContractAt(name: 'IUniversalRouter', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IUniversalRouter>
getContractAt(name: 'IWETH', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IWETH>
getContractAt(name: 'Permit2', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.Permit2>
getContractAt(name: 'UniswapV4Example', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.UniswapV4Example>
getContractAt(name: 'ICurveExchange', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ICurveExchange>
getContractAt(name: 'ICurvePool', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ICurvePool>
getContractAt(name: 'INotional', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.INotional>

  deployContract(name: 'CurveExample', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.CurveExample>
deployContract(name: 'IWETH', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IWETH>
deployContract(name: 'AaveExample', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.AaveExample>
deployContract(name: 'ConvexExample', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ConvexExample>
deployContract(name: 'IConvex', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IConvex>
deployContract(name: 'NotionalExample', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.NotionalExample>
deployContract(name: 'IWETH', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IWETH>
deployContract(name: 'UniswapV3Example', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.UniswapV3Example>
deployContract(name: 'IUniversalRouter', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IUniversalRouter>
deployContract(name: 'IWETH', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IWETH>
deployContract(name: 'Permit2', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Permit2>
deployContract(name: 'UniswapV4Example', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.UniswapV4Example>
deployContract(name: 'ICurveExchange', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ICurveExchange>
deployContract(name: 'ICurvePool', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ICurvePool>
deployContract(name: 'INotional', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.INotional>

  deployContract(name: 'CurveExample', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.CurveExample>
deployContract(name: 'IWETH', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IWETH>
deployContract(name: 'AaveExample', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.AaveExample>
deployContract(name: 'ConvexExample', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ConvexExample>
deployContract(name: 'IConvex', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IConvex>
deployContract(name: 'NotionalExample', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.NotionalExample>
deployContract(name: 'IWETH', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IWETH>
deployContract(name: 'UniswapV3Example', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.UniswapV3Example>
deployContract(name: 'IUniversalRouter', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IUniversalRouter>
deployContract(name: 'IWETH', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IWETH>
deployContract(name: 'Permit2', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Permit2>
deployContract(name: 'UniswapV4Example', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.UniswapV4Example>
deployContract(name: 'ICurveExchange', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ICurveExchange>
deployContract(name: 'ICurvePool', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ICurvePool>
deployContract(name: 'INotional', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.INotional>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  