/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../../common.js"
  

  export interface UniswapV3ExampleInterface extends Interface {
    getFunction(nameOrSignature: "getWETH" | "owner" | "swap" | "withdrawETH" | "withdrawTokens"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'getWETH', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'swap', values: [AddressLike[], BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'withdrawETH', values?: undefined): string;
encodeFunctionData(functionFragment: 'withdrawTokens', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'getWETH', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'swap', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdrawETH', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdrawTokens', data: BytesLike): Result;
  }

  

  export interface UniswapV3Example extends BaseContract {
    
    connect(runner?: ContractRunner | null): UniswapV3Example;
    waitForDeployment(): Promise<this>;

    interface: UniswapV3ExampleInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    getWETH: TypedContractMethod<
      [],
      [void],
      'payable'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    swap: TypedContractMethod<
      [_path: AddressLike[], _fee: BigNumberish, _amountIn: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    withdrawETH: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    withdrawTokens: TypedContractMethod<
      [_token: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'getWETH'): TypedContractMethod<
      [],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'swap'): TypedContractMethod<
      [_path: AddressLike[], _fee: BigNumberish, _amountIn: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'withdrawETH'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'withdrawTokens'): TypedContractMethod<
      [_token: AddressLike, ],
      [void],
      'nonpayable'
    >;

    

    filters: {
      
    };
  }