/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../../common.js"
  
    export type PoolKeyStruct = {currency0: AddressLike, currency1: AddressLike, fee: BigNumberish, tickSpacing: BigNumberish, hooks: AddressLike}

    export type PoolKeyStructOutput = [currency0: string, currency1: string, fee: bigint, tickSpacing: bigint, hooks: string] & {currency0: string, currency1: string, fee: bigint, tickSpacing: bigint, hooks: string }
  

  export interface UniswapV4ExampleInterface extends Interface {
    getFunction(nameOrSignature: "USDC" | "WETH" | "approveTokenWithPermit2" | "executeTrade" | "getBalance" | "getWETH" | "permit2" | "router"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'USDC', values?: undefined): string;
encodeFunctionData(functionFragment: 'WETH', values?: undefined): string;
encodeFunctionData(functionFragment: 'approveTokenWithPermit2', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'executeTrade', values: [PoolKeyStruct, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getBalance', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'getWETH', values?: undefined): string;
encodeFunctionData(functionFragment: 'permit2', values?: undefined): string;
encodeFunctionData(functionFragment: 'router', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'USDC', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'WETH', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'approveTokenWithPermit2', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'executeTrade', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getBalance', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getWETH', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'permit2', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'router', data: BytesLike): Result;
  }

  

  export interface UniswapV4Example extends BaseContract {
    
    connect(runner?: ContractRunner | null): UniswapV4Example;
    waitForDeployment(): Promise<this>;

    interface: UniswapV4ExampleInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    USDC: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    WETH: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    approveTokenWithPermit2: TypedContractMethod<
      [token: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    executeTrade: TypedContractMethod<
      [key: PoolKeyStruct, amountIn: BigNumberish, minAmountOut: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    getBalance: TypedContractMethod<
      [token: AddressLike, user: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    getWETH: TypedContractMethod<
      [],
      [void],
      'payable'
    >
    

    
    permit2: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    router: TypedContractMethod<
      [],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'USDC'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'WETH'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'approveTokenWithPermit2'): TypedContractMethod<
      [token: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'executeTrade'): TypedContractMethod<
      [key: PoolKeyStruct, amountIn: BigNumberish, minAmountOut: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getBalance'): TypedContractMethod<
      [token: AddressLike, user: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getWETH'): TypedContractMethod<
      [],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'permit2'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'router'): TypedContractMethod<
      [],
      [string],
      'view'
    >;

    

    filters: {
      
    };
  }