/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as uniswapV3ExampleSol from './UniswapV3Example.sol/index.js';
export type { uniswapV3ExampleSol };
import type * as uniswapV4ExampleSol from './UniswapV4Example.sol/index.js';
export type { uniswapV4ExampleSol };