/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface CurveExampleInterface extends Interface {
    getFunction(nameOrSignature: "addLiquidityToCurve" | "getBestPool" | "getLPAddress" | "getWETH" | "owner" | "swapOnCurve"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'addLiquidityToCurve', values: [[AddressLike, AddressLike], [BigNumberish, BigNumberish], AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getBestPool', values: [[AddressLike, AddressLike], BigNumberish]): string;
encodeFunctionData(functionFragment: 'getLPAddress', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getWETH', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'swapOnCurve', values: [AddressLike, [AddressLike, AddressLike], BigNumberish, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'addLiquidityToCurve', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getBestPool', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getLPAddress', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getWETH', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'swapOnCurve', data: BytesLike): Result;
  }

  

  export interface CurveExample extends BaseContract {
    
    connect(runner?: ContractRunner | null): CurveExample;
    waitForDeployment(): Promise<this>;

    interface: CurveExampleInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    addLiquidityToCurve: TypedContractMethod<
      [_tokens: [AddressLike, AddressLike], _amounts: [BigNumberish, BigNumberish], _pool: AddressLike, _expected: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    getBestPool: TypedContractMethod<
      [_path: [AddressLike, AddressLike], _amount: BigNumberish, ],
      [string],
      'view'
    >
    

    
    getLPAddress: TypedContractMethod<
      [_pool: AddressLike, ],
      [string],
      'view'
    >
    

    
    getWETH: TypedContractMethod<
      [],
      [void],
      'payable'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    swapOnCurve: TypedContractMethod<
      [_pool: AddressLike, _path: [AddressLike, AddressLike], _amount: BigNumberish, _expected: BigNumberish, ],
      [void],
      'payable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'addLiquidityToCurve'): TypedContractMethod<
      [_tokens: [AddressLike, AddressLike], _amounts: [BigNumberish, BigNumberish], _pool: AddressLike, _expected: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getBestPool'): TypedContractMethod<
      [_path: [AddressLike, AddressLike], _amount: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getLPAddress'): TypedContractMethod<
      [_pool: AddressLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getWETH'): TypedContractMethod<
      [],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'swapOnCurve'): TypedContractMethod<
      [_pool: AddressLike, _path: [AddressLike, AddressLike], _amount: BigNumberish, _expected: BigNumberish, ],
      [void],
      'payable'
    >;

    

    filters: {
      
    };
  }