/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface AaveExampleInterface extends Interface {
    getFunction(nameOrSignature: "AAVE_POOL_ADDRESS" | "AAVE_REWARDS_ADDRESS" | "AAVE_WETH" | "USDC_ADDRESS" | "WETH_ADDRESS" | "borrowAave" | "getRewardsInfoForContract" | "getRewardsInfoForToken" | "getTokenBalance" | "owner" | "repayAave" | "supplyAave" | "withdrawAave"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'AAVE_POOL_ADDRESS', values?: undefined): string;
encodeFunctionData(functionFragment: 'AAVE_REWARDS_ADDRESS', values?: undefined): string;
encodeFunctionData(functionFragment: 'AAVE_WETH', values?: undefined): string;
encodeFunctionData(functionFragment: 'USDC_ADDRESS', values?: undefined): string;
encodeFunctionData(functionFragment: 'WETH_ADDRESS', values?: undefined): string;
encodeFunctionData(functionFragment: 'borrowAave', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getRewardsInfoForContract', values: [AddressLike[]]): string;
encodeFunctionData(functionFragment: 'getRewardsInfoForToken', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getTokenBalance', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'repayAave', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'supplyAave', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'withdrawAave', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'AAVE_POOL_ADDRESS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'AAVE_REWARDS_ADDRESS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'AAVE_WETH', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'USDC_ADDRESS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'WETH_ADDRESS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'borrowAave', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRewardsInfoForContract', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRewardsInfoForToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getTokenBalance', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'repayAave', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'supplyAave', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdrawAave', data: BytesLike): Result;
  }

  

  export interface AaveExample extends BaseContract {
    
    connect(runner?: ContractRunner | null): AaveExample;
    waitForDeployment(): Promise<this>;

    interface: AaveExampleInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    AAVE_POOL_ADDRESS: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    AAVE_REWARDS_ADDRESS: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    AAVE_WETH: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    USDC_ADDRESS: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    WETH_ADDRESS: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    borrowAave: TypedContractMethod<
      [_amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    getRewardsInfoForContract: TypedContractMethod<
      [_tokens: AddressLike[], ],
      [[string[], bigint[]]],
      'view'
    >
    

    
    getRewardsInfoForToken: TypedContractMethod<
      [_token: AddressLike, ],
      [string[]],
      'view'
    >
    

    
    getTokenBalance: TypedContractMethod<
      [_token: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    repayAave: TypedContractMethod<
      [_token: AddressLike, _amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    supplyAave: TypedContractMethod<
      [_amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    withdrawAave: TypedContractMethod<
      [_amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'AAVE_POOL_ADDRESS'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'AAVE_REWARDS_ADDRESS'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'AAVE_WETH'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'USDC_ADDRESS'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'WETH_ADDRESS'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'borrowAave'): TypedContractMethod<
      [_amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getRewardsInfoForContract'): TypedContractMethod<
      [_tokens: AddressLike[], ],
      [[string[], bigint[]]],
      'view'
    >;
getFunction(nameOrSignature: 'getRewardsInfoForToken'): TypedContractMethod<
      [_token: AddressLike, ],
      [string[]],
      'view'
    >;
getFunction(nameOrSignature: 'getTokenBalance'): TypedContractMethod<
      [_token: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'repayAave'): TypedContractMethod<
      [_token: AddressLike, _amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'supplyAave'): TypedContractMethod<
      [_amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'withdrawAave'): TypedContractMethod<
      [_amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    

    filters: {
      
    };
  }