/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interfaces from './interfaces/index.js';
export type { interfaces };
export type { NotionalExample } from './NotionalExample.js';