/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BytesLike, FunctionFragment, Result, Interface, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface NotionalExampleInterface extends Interface {
    getFunction(nameOrSignature: "borrow" | "deposit" | "getBalance" | "getCollateralView" | "redeem" | "supply"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'borrow', values?: undefined): string;
encodeFunctionData(functionFragment: 'deposit', values?: undefined): string;
encodeFunctionData(functionFragment: 'getBalance', values?: undefined): string;
encodeFunctionData(functionFragment: 'getCollateralView', values?: undefined): string;
encodeFunctionData(functionFragment: 'redeem', values?: undefined): string;
encodeFunctionData(functionFragment: 'supply', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'borrow', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'deposit', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getBalance', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getCollateralView', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'redeem', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'supply', data: BytesLike): Result;
  }

  

  export interface NotionalExample extends BaseContract {
    
    connect(runner?: ContractRunner | null): NotionalExample;
    waitForDeployment(): Promise<this>;

    interface: NotionalExampleInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    borrow: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    deposit: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    getBalance: TypedContractMethod<
      [],
      [[bigint, bigint, bigint]],
      'view'
    >
    

    
    getCollateralView: TypedContractMethod<
      [],
      [[bigint, bigint[]]],
      'view'
    >
    

    
    redeem: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    supply: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'borrow'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'deposit'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getBalance'): TypedContractMethod<
      [],
      [[bigint, bigint, bigint]],
      'view'
    >;
getFunction(nameOrSignature: 'getCollateralView'): TypedContractMethod<
      [],
      [[bigint, bigint[]]],
      'view'
    >;
getFunction(nameOrSignature: 'redeem'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'supply'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;

    

    filters: {
      
    };
  }