/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { Permit2, Permit2Interface } from "../../../Uniswap/UniswapV4Example.sol/Permit2.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      },
      {
        "internalType": "uint160",
        "name": "",
        "type": "uint160"
      },
      {
        "internalType": "uint48",
        "name": "",
        "type": "uint48"
      }
    ],
    "name": "approve",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  export class Permit2__factory {
    static readonly abi = _abi;
    static createInterface(): Permit2Interface {
      return new Interface(_abi) as Permit2Interface;
    }
    static connect(address: string, runner?: ContractRunner | null): Permit2 {
      return new Contract(address, _abi, runner) as unknown as Permit2;
    }
  }
  