/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../../../common.js"
  import type { ConvexExample, ConvexExampleInterface } from "../../../Convex/ConvexExample.sol/ConvexExample.js";

  const _abi = [
  {
    "inputs": [],
    "stateMutability": "nonpayable",
    "type": "constructor"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "_amount",
        "type": "uint256"
      }
    ],
    "name": "depositCRV",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  const _bytecode = "0x608060405234801561001057600080fd5b50610394806100206000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c80639f2efe7914610030575b600080fd5b61004a600480360381019061004591906101c8565b61004c565b005b73971add32ea87f10bd192671630be3be8a11b862373ffffffffffffffffffffffffffffffffffffffff1663095ea7b373f403c135812408bfbe8713b5a23a04b3d48aae31836040518363ffffffff1660e01b81526004016100af929190610245565b6020604051808303816000875af11580156100ce573d6000803e3d6000fd5b505050506040513d601f19601f820116820180604052508101906100f291906102a6565b5073f403c135812408bfbe8713b5a23a04b3d48aae3173ffffffffffffffffffffffffffffffffffffffff166343a0d066609d8360016040518463ffffffff1660e01b815260040161014693929190610327565b6020604051808303816000875af1158015610165573d6000803e3d6000fd5b505050506040513d601f19601f8201168201806040525081019061018991906102a6565b5050565b600080fd5b6000819050919050565b6101a581610192565b81146101b057600080fd5b50565b6000813590506101c28161019c565b92915050565b6000602082840312156101de576101dd61018d565b5b60006101ec848285016101b3565b91505092915050565b600073ffffffffffffffffffffffffffffffffffffffff82169050919050565b6000610220826101f5565b9050919050565b61023081610215565b82525050565b61023f81610192565b82525050565b600060408201905061025a6000830185610227565b6102676020830184610236565b9392505050565b60008115159050919050565b6102838161026e565b811461028e57600080fd5b50565b6000815190506102a08161027a565b92915050565b6000602082840312156102bc576102bb61018d565b5b60006102ca84828501610291565b91505092915050565b6000819050919050565b6000819050919050565b60006103026102fd6102f8846102d3565b6102dd565b610192565b9050919050565b610312816102e7565b82525050565b6103218161026e565b82525050565b600060608201905061033c6000830186610309565b6103496020830185610236565b6103566040830184610318565b94935050505056fea26469706673582212206fb599185053c7e19ab90d955e24829b4699a0614eee78f23115855dd1104b1164736f6c63430008130033";

  
      type ConvexExampleConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: ConvexExampleConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class ConvexExample__factory extends ContractFactory {
    
      constructor(...args: ConvexExampleConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(overrides || {});
    };
    override deploy(overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(overrides || {}) as Promise<ConvexExample & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): ConvexExample__factory {
      return super.connect(runner) as ConvexExample__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): ConvexExampleInterface {
      return new Interface(_abi) as ConvexExampleInterface;
    }
    
    override attach(address: string | Addressable): ConvexExample {
      return super.attach(address) as ConvexExample;
    }
  static connect(address: string, runner?: ContractRunner | null): ConvexExample {
      return new Contract(address, _abi, runner) as unknown as ConvexExample;
    }
  }

  
  