/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ConvexExample__factory } from './ConvexExample__factory.js';
export { IConvex__factory } from './IConvex__factory.js';