/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface ICurveExchangeInterface extends Interface {
    getFunction(nameOrSignature: "exchange" | "get_best_rate"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'exchange', values: [AddressLike, AddressLike, AddressLike, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'get_best_rate', values: [AddressLike, AddressLike, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'exchange', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'get_best_rate', data: BytesLike): Result;
  }

  

  export interface ICurveExchange extends BaseContract {
    
    connect(runner?: ContractRunner | null): ICurveExchange;
    waitForDeployment(): Promise<this>;

    interface: ICurveExchangeInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    exchange: TypedContractMethod<
      [_pool: AddressLike, _from: AddressLike, _to: AddressLike, _amount: BigNumberish, _expected: BigNumberish, ],
      [bigint],
      'payable'
    >
    

    
    get_best_rate: TypedContractMethod<
      [_from: AddressLike, _to: AddressLike, _amount: BigNumberish, ],
      [[string, bigint]],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'exchange'): TypedContractMethod<
      [_pool: AddressLike, _from: AddressLike, _to: AddressLike, _amount: BigNumberish, _expected: BigNumberish, ],
      [bigint],
      'payable'
    >;
getFunction(nameOrSignature: 'get_best_rate'): TypedContractMethod<
      [_from: AddressLike, _to: AddressLike, _amount: BigNumberish, ],
      [[string, bigint]],
      'view'
    >;

    

    filters: {
      
    };
  }