/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface ICurvePoolInterface extends Interface {
    getFunction(nameOrSignature: "add_liquidity(uint256[2],uint256)" | "add_liquidity(uint256[3],uint256)" | "token"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'add_liquidity(uint256[2],uint256)', values: [[BigNumberish, BigNumberish], BigNumberish]): string;
encodeFunctionData(functionFragment: 'add_liquidity(uint256[3],uint256)', values: [[BigNumberish, BigNumberish, BigNumberish], BigNumberish]): string;
encodeFunctionData(functionFragment: 'token', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'add_liquidity(uint256[2],uint256)', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'add_liquidity(uint256[3],uint256)', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'token', data: BytesLike): Result;
  }

  

  export interface ICurvePool extends BaseContract {
    
    connect(runner?: ContractRunner | null): ICurvePool;
    waitForDeployment(): Promise<this>;

    interface: ICurvePoolInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    "add_liquidity(uint256[2],uint256)": TypedContractMethod<
      [amounts: [BigNumberish, BigNumberish], min_mint_amount: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    

    
    "add_liquidity(uint256[3],uint256)": TypedContractMethod<
      [amounts: [BigNumberish, BigNumberish, BigNumberish], min_mint_amount: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    

    
    token: TypedContractMethod<
      [],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'add_liquidity(uint256[2],uint256)'): TypedContractMethod<
      [amounts: [BigNumberish, BigNumberish], min_mint_amount: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'add_liquidity(uint256[3],uint256)'): TypedContractMethod<
      [amounts: [BigNumberish, BigNumberish, BigNumberish], min_mint_amount: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'token'): TypedContractMethod<
      [],
      [string],
      'view'
    >;

    

    filters: {
      
    };
  }