/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../../common.js"
  
export declare namespace INotional {
      
    export type BalanceActionWithTradesStruct = {actionType: BigNumberish, currencyId: BigNumberish, depositActionAmount: BigNumberish, withdrawAmountInternalPrecision: BigNumberish, withdrawEntireCashBalance: boolean, redeemToUnderlying: boolean, trades: BytesLike[]}

    export type BalanceActionWithTradesStructOutput = [actionType: bigint, currencyId: bigint, depositActionAmount: bigint, withdrawAmountInternalPrecision: bigint, withdrawEntireCashBalance: boolean, redeemToUnderlying: boolean, trades: string[]] & {actionType: bigint, currencyId: bigint, depositActionAmount: bigint, withdrawAmountInternalPrecision: bigint, withdrawEntireCashBalance: boolean, redeemToUnderlying: boolean, trades: string[] }
  
    }

  export interface INotionalInterface extends Interface {
    getFunction(nameOrSignature: "batchBalanceAndTradeAction" | "depositUnderlyingToken" | "getAccountBalance" | "getFreeCollateral" | "withdraw"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'batchBalanceAndTradeAction', values: [AddressLike, INotional.BalanceActionWithTradesStruct[]]): string;
encodeFunctionData(functionFragment: 'depositUnderlyingToken', values: [AddressLike, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getAccountBalance', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'getFreeCollateral', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'withdraw', values: [BigNumberish, BigNumberish, boolean]): string;

    decodeFunctionResult(functionFragment: 'batchBalanceAndTradeAction', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'depositUnderlyingToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAccountBalance', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getFreeCollateral', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdraw', data: BytesLike): Result;
  }

  

  export interface INotional extends BaseContract {
    
    connect(runner?: ContractRunner | null): INotional;
    waitForDeployment(): Promise<this>;

    interface: INotionalInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    batchBalanceAndTradeAction: TypedContractMethod<
      [account: AddressLike, actions: INotional.BalanceActionWithTradesStruct[], ],
      [void],
      'payable'
    >
    

    
    depositUnderlyingToken: TypedContractMethod<
      [account: AddressLike, currencyId: BigNumberish, amountExternalPrecision: BigNumberish, ],
      [bigint],
      'payable'
    >
    

    
    getAccountBalance: TypedContractMethod<
      [currencyId: BigNumberish, account: AddressLike, ],
      [[bigint, bigint, bigint]],
      'view'
    >
    

    
    getFreeCollateral: TypedContractMethod<
      [account: AddressLike, ],
      [[bigint, bigint[]]],
      'view'
    >
    

    
    withdraw: TypedContractMethod<
      [currencyId: BigNumberish, amountInternalPrecision: BigNumberish, redeemToUnderlying: boolean, ],
      [bigint],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'batchBalanceAndTradeAction'): TypedContractMethod<
      [account: AddressLike, actions: INotional.BalanceActionWithTradesStruct[], ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'depositUnderlyingToken'): TypedContractMethod<
      [account: AddressLike, currencyId: BigNumberish, amountExternalPrecision: BigNumberish, ],
      [bigint],
      'payable'
    >;
getFunction(nameOrSignature: 'getAccountBalance'): TypedContractMethod<
      [currencyId: BigNumberish, account: AddressLike, ],
      [[bigint, bigint, bigint]],
      'view'
    >;
getFunction(nameOrSignature: 'getFreeCollateral'): TypedContractMethod<
      [account: AddressLike, ],
      [[bigint, bigint[]]],
      'view'
    >;
getFunction(nameOrSignature: 'withdraw'): TypedContractMethod<
      [currencyId: BigNumberish, amountInternalPrecision: BigNumberish, redeemToUnderlying: boolean, ],
      [bigint],
      'nonpayable'
    >;

    

    filters: {
      
    };
  }